### ISSUE TITLE
Windows release does not print the move lines

### ISSUE THREAD

**Issue by PritchardBarry** [andymac-2/milestoneMap#55]
I noticed that the pdf produced by the Windows release does not print the pink lines indicating milestone movement.

![windows pdf printing](https://user-images.githubusercontent.com/38608315/41808382-26148b42-770f-11e8-99f2-1dfd0e7fbec6.PNG)

**Comment by andymac-2** [comment]
I'm deprecating the native electron builds for milestoneMap until there is significant need to support them in the future.
