### ISSUE TITLE
Allow json files to be saved to Dropbox in IOS (iPad)

### ISSUE THREAD

**Issue by PritchardBarry** [andymac-2/milestoneMap#59]

**Comment by PritchardBarry** [comment]
I can open a JSON file from drop box.

I can’t save files to a given location on the iPad. I can save a CSV by using the default export/share to the Files app. 

Would be great to be able to save a JSON file and export to the Files app.

**Comment by andymac-2** [comment]
I don't believe this is an issue with milestone map, the exact same code is
used to download a CSV as it is to download JSON.

This is most likely an issue with the ipad API. I also have no ability to
test this.

**Comment by andymac-2** [comment]
Fixed for 
e9bcf85
